SolutionsLeatherGoods/Presentation/ASF.UI.WbSite/Controllers/CartController.cs
using ASF.Data.DbContext;
using ASF.UI.Process;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ASF.UI.WbSite.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        [HttpGet]
        public ActionResult Index(string language)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);

            var email = User.Identity.Name;
            var cartProcess = new CartProcess();
            var cartCompleta = cartProcess.ObtenerCartCompleta(email);

            return View(cartCompleta);
        }

        [HttpPost]
        public ActionResult UpdateCart(int cantidad, int productId, double price)
        {
            var email = User.Identity.Name;
            var cartProcess = new CartProcess();

            cartProcess.AddToCart(cantidad, productId, email, price);

            return RedirectToAction("Index", "Product");
        }

        public ActionResult Remove(int id)
        {
            var cartProcess = new CartProcess();
            cartProcess.Remove(id);

            return RedirectToAction("Index", "Cart");
        }

        public ActionResult Images(int id)
        {
            var context = new LeatherGoodsEntities();
            byte[] imageData = context.Product.FirstOrDefault(i => i.Id == id)?.Image;
            if (imageData != null)
            {
                return File(imageData, "image/png", "image/jpg");
            }
            return null;
        }
    }
}

SolutionsLeatherGoods/Presentation/ASF.UI.WbSite/Controllers/CheckOutController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace ASF.UI.WbSite.Controllers
{
    public class CheckOutController : Controller
    {
        // GET: CheckOut
        public ActionResult Index(string language)
        {

            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);

            return View();
        }

        public ActionResult CheckOut()
        {
            return View();
        }
    }
}

SolutionsLeatherGoods/Presentation/ASF.UI.WbSite/Controllers/ProductController.cs
using ASF.Data.DbContext;
using ASF.UI.Process;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASF.Entities;
using System.IO;
using System.Threading;
using System.Globalization;

namespace ASF.UI.WbSite.Controllers
{
    public class ProductController : Controller
    {

        private List<Data.DbContext.Product> MapperProduct(IQueryable<Data.DbContext.Product> ListaRecibida)
        {
            List<Data.DbContext.Product> ListaProduct = new List<Data.DbContext.Product>();

            foreach (Data.DbContext.Product i in ListaRecibida)
            {
                var product = new Data.DbContext.Product();

                product.Id = i.Id;
                product.Image = i.Image;
                product.Price = i.Price;
                product.QuantitySold = i.QuantitySold;
                product.Rating = i.Rating;
                product.Title = i.Title;
                product.AvgStars = i.AvgStars;
                product.DealerId = i.DealerId;
                product.Description = i.Description;

                ListaProduct.Add(product);
            }

            return ListaProduct;
        }



        // GET: Product
        
        public ActionResult Index(string language)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);

            if (User.Identity.IsAuthenticated)
            {
                var productProcess = new ProductProcess();
                var listaProduct = productProcess.SelectAll();
                return View(listaProduct);
            }

            else
            { 

                return RedirectToAction("LogIn", "Account");
            }
            
            
        }

        public ActionResult ProductDetail(int id,string language)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);

            var context = new LeatherGoodsEntities();
            //byte[] imageData = context.Product.FirstOrDefault(i => i.Id == id)?.Image;
            //if (imageData != null)
            //{
            //    return File(imageData, "image/jpg"); // Might need to adjust the content type based on your actual image type
            //}

            Data.DbContext.Product product = new Data.DbContext.Product();

            var consulta = from products in context.Product
                           where products.Id == id
                           select products;

            var p = MapperProduct(consulta)[0];

            return View(p);
        }


        public ActionResult Images(int id)
        {
            var context = new LeatherGoodsEntities();
            byte[] imageData = context.Product.FirstOrDefault(i => i.Id == id)?.Image;
            if (imageData != null)
            {
                return File(imageData, "image/png", "image/jpg");
            }
            return null;
        }


        [HttpGet]
        public ActionResult Create(string language)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(language);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(language);

            var listaProduct = new List<Entities.Product>();
            var dealerProcess = new DelaerProcess();

            var listaDealer = dealerProcess.SelectAll();

            foreach (var i in listaDealer)
            {
                var product = new Entities.Product();
                        product.DealerId = i.Id;
                product.DealerDesc = i.Description;

                listaProduct.Add(product);
            }
            ViewBag.dealer = listaDealer;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Data.DbContext.Product product, HttpPostedFileBase file)
        {
            var context = new LeatherGoodsEntities();


            if (file != null)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    byte[] array = ms.GetBuffer();

                    product.Image = array;
                }

            }

            context.Product.Add(product);
            context.SaveChanges();

            return RedirectToAction("Index");
        }




        public ActionResult addTocart()
        {
            return View();
        }
    }
}

SolutionsLeatherGoods/Presentation/ASF.UI.WbSite/Views/Cart/Index.cshtml
@model ASF.UI.Process.CartCompleta
@{
    ViewBag.Title = "Index";
    var total = 0;
}

<style>
   
</style>


<div class="container">
    <div class="row">
        <div class="col-xs-12 col-xs-10 col-xs-offset-1">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th class="text-center">@ASF.UI.WbSite.Resources.MyText.Product</th>
                        <th class="text-left">@ASF.UI.WbSite.Resources.MyText.Description</th>                        
                        <th class="text-center">@ASF.UI.WbSite.Resources.MyText.Quantity</th>
                        <th class="text-center">@ASF.UI.WbSite.Resources.MyText.Price</th>
                        <th class="text-center">@ASF.UI.WbSite.Resources.MyText.Total</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>  
                   
                @foreach (var item in Model.detalle)
                {
                    var subtotal = item.Price * item.Quantity;
                  
                    total = total +Convert.ToInt32(subtotal);
                    <tr>
                        <td class="col-xs-8 col-xs-2">
                            <br />
                            <div>
                                <img src="@Url.Action("Images", "Cart", new { id = item.ProductId })" style="text-align:center; vertical-align:middle" width="90" height="90" />
                            </div>
                              
                        </td>
                        <td>
                            <br />
                            <br />
                          
                            <div >
                                <h4>@item.Pdescripcion</h4>
                            </div>
                        </td>
                       
                        <td class="col-md-1 col-md-1" style="text-align: center" height="160.56">
                            <br />
                            <br />
                            
                            <h5><strong>@item.Quantity</strong></h5>
                        </td>
                        <td class="col-xs-1 col-xs-1 text-center">
                            <br />
                            <br />
                            <h4> <strong>$@item.Price</strong></h4>
                        </td>
                        <td class="col-xs-1 col-xs-1 text-center">
                            <br />
                            <br />                            
                            <h5><strong>$@subtotal</strong></h5>
                        </td>
                        <td class="col-xs-1 col-xs-1">
                            <br />
                            <br />                          
                            @*@Html.ActionLink("Detalles", "ProductDetail", new { id = item.Id }, new { @class = "btn btn-primary" })*@
                            <a href="@Url.Action("Remove", "Cart",new { id = item.Id})", style="font-size:26px" class="fa fa-remove">                                
                            </a>

                            @*<button type="button" class="btn btn-danger">
                              
                                <span class="fa fa-remove"></span> Remove
                            </button>*@
                        </td>
                    </tr>
                }
                    
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td><h3>@ASF.UI.WbSite.Resources.MyText.Total</h3></td>
                        <td class="text-right"><h3><strong>$@total</strong></h3></td>
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td>
                           
                            @*<a href="@Url.Action("Index", "Product")" class="btn btn-primary">                               
                                <span id="span" class="fa fa-shopping-cart"> Continue Shopping</span>
                            </a>*@
                            @Html.ActionLink(@ASF.UI.WbSite.Resources.MyText.ContinueShopping, "Index", "Product",null, new { @class = "btn btn-info" })

                            @*<li><a id="a" href="@Url.Action("Index","Product")"><span aria-hidden="true" class="btn btn-success fa-shopping-cart"></span> ContinueShopping</a></li>*@
                        </td>
                        <td>
                            @Html.ActionLink(@ASF.UI.WbSite.Resources.MyText.CheckOut, "Index", "CheckOut", null, new { @class = "btn btn-success" })
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>









@*<h2>Index</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Cart</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IdUser, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IdUser, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IdUser, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CartDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CartDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ItemCount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ItemCount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ItemCount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Rowid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Rowid, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Rowid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ChangedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChangedOn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChangedOn, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ChangedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChangedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChangedBy, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@